
class Config {

  /// Generated by Flangapp PRO 17-07-2025 15:39
  /// App UID: 64f4ee9c-daa4-f63c-0013-2f871e7004c7
  /// Version: 1.0.2
  /// API server: https://api.appmyweb.net/

  /// *** Main settings *** ///
  static String apiUrl = "https://api.appmyweb.net/";
  static String appUid = "64f4ee9c-daa4-f63c-0013-2f871e7004c7";
  static String oneSignalPushId = "7ede92c8-3e28-4bb5-b8bc-362355d55d2b";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#F44336";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = false;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}