
class Config {

  /// Generated by Flangapp PRO 17-07-2025 16:18
  /// App UID: bc6f8cc1-61e8-742f-d772-bf4ef8555ace
  /// Version: 1.0.0
  /// API server: https://api.appmyweb.net/

  /// *** Main settings *** ///
  static String apiUrl = "https://api.appmyweb.net/";
  static String appUid = "bc6f8cc1-61e8-742f-d772-bf4ef8555ace";
  static String oneSignalPushId = "81736486-3b8e-432c-8d12-8365e53d70f5";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#0A0226";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "best mobile apps builder";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = true;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}