
class Config {

  /// Generated by Flangapp PRO 23-01-2025 21:36
  /// App UID: 7ff93bca-65ae-be08-87bb-48ce55a37ba8
  /// Version: 1.1.2
  /// API server: https://api.appmyweb.net/

  /// *** Main settings *** ///
  static String apiUrl = "https://api.appmyweb.net/";
  static String appUid = "7ff93bca-65ae-be08-87bb-48ce55a37ba8";
  static String oneSignalPushId = "4a9acee4-d9d1-45f4-8ff7-982be6bec867";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#78BACC";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "a p p i r o n";
  // Delay display (seconds)
  static int splashDelay = 0;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = false;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}